### PR TITLE
Create Shared Function Module

### PR DESCRIPTION
**Pull request by A9G-Data-Droid**
I split all the business logic out in to a module that can be shared between the GUI and command line versions. Now you can maintain the action in one place. I apologize for the large number of changed lines this major refactoring has caused.

The flow and functionality is largely the same. Big improvement for the GUI is that I made some background jobs that show an animation in the GUI instead of becoming unresponsive. It also downloads multithreaded so all downloads will occur simultaneously. This is a huge performance boost.

The install script is now a PS1 instead of a BAT.

I changed the way to GUI looks a bit.

I have tested both the GUI and the command line versions. All appears to be working as expected.

### CODE REVIEW

**Comment by julrich-usgs** [comment]
Nice.  I will check it out sometime.  I got it up and working to solve a problem and never had time to improve it.  I don't think I have to do anything since you made your own branch, but I've never used GitHub before, so if you need me to do something let me know.  I don't have time to read the GitHub tutorial right now either LOL!

**Comment by julrich-usgs** [comment]
Do I need to "Merge pull request"?  And if so, which option do I want... "merge commit" "squash" "rebase" slightly embarrassing that I have no idea.

**Comment by A9G-Data-Droid** [comment]
Welcome to Github. When someone submits a pull request (PR) to you here is what you want to do:

1. Review the incoming code changes
2. Test the new version

If you agree with the changes and the testing went well then you want to merge commit. 

Git can get very complicated and I am no expert. It's worth learning. The idea is that multiple people around the world can use and improve a project over time. If you are tired of maintaining a repository you can point users at a more active fork and make it clear that you won't be updating your fork anymore. This way, code can live on beyond the original developer.

**Comment by julrich-usgs** [comment]
I actually use the DoRemoteDriverUpdate over PSEXEC and the script is run from a network share.  I'll have to consider how to retain that functionality.

**Comment by A9G-Data-Droid** [comment]
I have tested that script using remote deployment software. Did your testing fail? What was the problem?

**Comment by julrich-usgs** [comment]
It's not really a problem, it's just that I centrally host scripts and other things of this nature and do a lot of remote execution.  I use taskpad view in ADUC and psexec for a lot of things similar to this:
`psexec.exe -s -h \\<name passed from Taskpad View> powershell.exe -ExecutionPolicy Bypass \\PathToYourServerWithCommonScripts\RemoteDriveUpdate.ps1
`

I'm pretty sure if I did this now, the PC would try to download it's updates to my remote server instead of storing them locally.``

**Comment by A9G-Data-Droid** [comment]
I see. Yes, I thought about that. The simple fix is to make a subfolder using %HOSTNAME% so that each machine gets it's own folder where the downloads and logs go. Then you can quickly look at the logs, etc.

**Pull request merged**
